<?php

namespace Tests\Feature;

use App\Models\EmailLog;
use App\Models\PrivacyRequest;
use App\Models\Shop;
use App\Models\User;
use Illuminate\Encryption\Encrypter;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class LaravelUpgradeCompatibilityTest extends TestCase
{
    use RefreshDatabase;

    public function test_laravel_10_encrypted_values_remain_readable_without_key_rotation(): void
    {
        // Synthetic ciphertext generated by Laravel 10.50.3 before this upgrade.
        // This deliberately public test key is unrelated to any application environment.
        $fixture = json_decode(file_get_contents(__DIR__.'/../Fixtures/laravel10-encryption.json'), true, flags: JSON_THROW_ON_ERROR);
        $this->assertSame('10.50.3', $fixture['framework']);
        $encrypter = new Encrypter(str_repeat('x', 32), 'AES-256-CBC');
        Shop::encryptUsing($encrypter);
        try {
            $shop = (new Shop)->setRawAttributes(['access_token' => $fixture['token']]);
            $this->assertSame(['token' => 'synthetic-upgrade-token'], $shop->access_token);
            $this->assertArrayNotHasKey('access_token', $shop->toArray());
            $log = (new EmailLog)->setRawAttributes(['subject' => $fixture['subject'], 'rendered_body' => $fixture['body']]);
            $this->assertSame('Synthetic legacy subject', $log->subject);
            $this->assertSame('<p>Synthetic legacy body</p>', $log->rendered_body);
            $export = (new PrivacyRequest)->setRawAttributes(['export' => $fixture['export']]);
            $this->assertSame(['synthetic' => true], $export->export);
        } finally {
            Shop::encryptUsing(null);
        }
    }

    public function test_existing_sanctum_token_route_remains_authenticated_and_hides_credentials(): void
    {
        $this->getJson('/api/user')->assertUnauthorized();
        $user = User::factory()->create();
        $token = $user->createToken('upgrade-regression')->plainTextToken;
        $this->withToken($token)->getJson('/api/user')->assertOk()->assertJsonPath('id', $user->id)
            ->assertJsonMissingPath('password')->assertJsonMissingPath('remember_token');
    }
}
